CREATE TABLE CURSO (
  CURSO_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(70) UNIQUE NOT NULL,
  PRIMARY KEY(CURSO_ID)
);

CREATE TABLE EDITORA (
  EDITORA_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(70) UNIQUE NOT NULL,
  PRIMARY KEY(EDITORA_ID)
);

CREATE TABLE BIBLIOTECARIO (
  BIBLIOTECARIO_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(70) UNIQUE NULL,
  PRIMARY KEY(BIBLIOTECARIO_ID)
);

CREATE TABLE AUTOR (
  AUTOR_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME  VARCHAR(70) UNIQUE NOT NULL,
  PRIMARY KEY(AUTOR_ID)
);

CREATE TABLE LIVRO (
  LIVRO_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  EDITORA_ID INTEGER UNSIGNED NOT NULL,
  NOME VARCHAR(50) UNIQUE NOT NULL,
  ISBN VARCHAR(20) UNIQUE NOT NULL,
  FOTO VARCHAR(50) UNIQUE NULL,
  PRIMARY KEY(LIVRO_ID),
  INDEX LIVRO_FKIndex1(EDITORA_ID),
  FOREIGN KEY(EDITORA_ID)
    REFERENCES EDITORA(EDITORA_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE USUARIO (
  USUARIO_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CURSO_ID INTEGER UNSIGNED NOT NULL,
  NOME VARCHAR(70) NOT NULL,
  MATRICULA VARCHAR(12) UNIQUE NOT NULL,
  PRIMARY KEY(USUARIO_ID),
  INDEX USUARIO_FKIndex1(CURSO_ID),
  FOREIGN KEY(CURSO_ID)
    REFERENCES CURSO(CURSO_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE AUTOR_LIVRO (
  AUTOR_ID INTEGER UNSIGNED NOT NULL,
  LIVRO_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(AUTOR_ID, LIVRO_ID),
  INDEX AUTOR_has_LIVRO_FKIndex1(AUTOR_ID),
  INDEX AUTOR_has_LIVRO_FKIndex2(LIVRO_ID),
  FOREIGN KEY(AUTOR_ID)
    REFERENCES AUTOR(AUTOR_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(LIVRO_ID)
    REFERENCES LIVRO(LIVRO_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE EXEMPLAR (
  EXEMPLAR_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  LIVRO_ID INTEGER UNSIGNED NOT NULL,
  NUMEX INTEGER UNSIGNED NOT NULL,
  
  PRIMARY KEY(EXEMPLAR_ID),
  INDEX EXEMPLAR_FKIndex1(LIVRO_ID),
  FOREIGN KEY(LIVRO_ID)
    REFERENCES LIVRO(LIVRO_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE EMPRESTIMO (
  EMPRESTIMO_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  EXEMPLAR_ID INTEGER UNSIGNED NOT NULL,
  USUARIO_ID INTEGER UNSIGNED NOT NULL,
  BIBLIOTECARIO_ID INTEGER UNSIGNED NOT NULL,
  DATAENTREGA DATE NOT NULL,
  DATADEVOLUCAO DATE NULL,
  PRIMARY KEY(EMPRESTIMO_ID),
  INDEX EXEMPLAR_has_USUARIO_FKIndex1(EXEMPLAR_ID),
  INDEX EXEMPLAR_has_USUARIO_FKIndex2(USUARIO_ID),
  INDEX EMPRESTIMO_FKIndex3(BIBLIOTECARIO_ID),
  FOREIGN KEY(EXEMPLAR_ID)
    REFERENCES EXEMPLAR(EXEMPLAR_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(USUARIO_ID)
    REFERENCES USUARIO(USUARIO_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(BIBLIOTECARIO_ID)
    REFERENCES BIBLIOTECARIO(BIBLIOTECARIO_ID)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


